In [1]:
# importing libraries
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score,ConfusionMatrixDisplay
from sklearn.metrics import plot_confusion_matrix

In [3]:
df = pd.read_csv('/content/csv_result-ObesityDataSet_raw_and_data_sinthetic.csv')

In [4]:
df.head(10)

id  Gender   Age  Height  Weight family_history_with_overweight FAVC  FCVC  \
0   1  Female  21.0    1.62    64.0                            yes   no   2.0   
1   2  Female  21.0    1.52    56.0                            yes   no   3.0   
2   3    Male  23.0    1.80    77.0                            yes   no   2.0   
3   4    Male  27.0    1.80    87.0                             no   no   3.0   
4   5    Male  22.0    1.78    89.8                             no   no   2.0   
5   6    Male  29.0    1.62    53.0                             no  yes   2.0   
6   7  Female  23.0    1.50    55.0                            yes  yes   3.0   
7   8    Male  22.0    1.64    53.0                             no   no   2.0   
8   9    Male  24.0    1.78    64.0                            yes  yes   3.0   
9  10    Male  22.0    1.72    68.0                            yes  yes   2.0   

   NCP       CAEC SMOKE  CH2O  SCC  FAF  TUE        CALC  \
0  3.0  Sometimes    no   2.0   no  0.0  1.0          no   
1  3.0  Sometimes   yes   3.0  yes  3.0  0.0   Sometimes   
2  3.0  Sometimes    no   2.0   no  2.0  1.0  Frequently   
3  3.0  Sometimes    no   2.0   no  2.0  0.0  Frequently   
4  1.0  Sometimes    no   2.0   no  0.0  0.0   Sometimes   
5  3.0  Sometimes    no   2.0   no  0.0  0.0   Sometimes   
6  3.0  Sometimes    no   2.0   no  1.0  0.0   Sometimes   
7  3.0  Sometimes    no   2.0   no  3.0  0.0   Sometimes   
8  3.0  Sometimes    no   2.0   no  1.0  1.0  Frequently   
9  3.0  Sometimes    no   2.0   no  1.0  1.0          no   

                  MTRANS           NObeyesdad  
0  Public_Transportation        Normal_Weight  
1  Public_Transportation        Normal_Weight  
2  Public_Transportation        Normal_Weight  
3                Walking   Overweight_Level_I  
4  Public_Transportation  Overweight_Level_II  
5             Automobile        Normal_Weight  
6              Motorbike        Normal_Weight  
7  Public_Transportation        Normal_Weight  
8  Public_Transportation        Normal_Weight  
9  Public_Transportation        Normal_Weight

In [5]:
#data = data.drop(columns=['Height', 'Weight'])
print(df.shape)

(2111, 18)


In [7]:
columns = ["FCVC", "NCP", "CH2O", "TUE", "FAF"]

for col in columns:
    #round to nearest whole number
    df[col] = round(df[col]).astype('int') 

In [8]:
df.head()

id  Gender   Age  Height  Weight family_history_with_overweight FAVC  FCVC  \
0   1  Female  21.0    1.62    64.0                            yes   no     2   
1   2  Female  21.0    1.52    56.0                            yes   no     3   
2   3    Male  23.0    1.80    77.0                            yes   no     2   
3   4    Male  27.0    1.80    87.0                             no   no     3   
4   5    Male  22.0    1.78    89.8                             no   no     2   

   NCP       CAEC SMOKE  CH2O  SCC  FAF  TUE        CALC  \
0    3  Sometimes    no     2   no    0    1          no   
1    3  Sometimes   yes     3  yes    3    0   Sometimes   
2    3  Sometimes    no     2   no    2    1  Frequently   
3    3  Sometimes    no     2   no    2    0  Frequently   
4    1  Sometimes    no     2   no    0    0   Sometimes   

                  MTRANS           NObeyesdad  
0  Public_Transportation        Normal_Weight  
1  Public_Transportation        Normal_Weight  
2  Public_Transportation        Normal_Weight  
3                Walking   Overweight_Level_I  
4  Public_Transportation  Overweight_Level_II

In [33]:
cleanup_nums = {"Gender":     {"Male": 0, "Female": 1},
                  "family_history_with_overweight": {"yes": 1, "no":0},
                  "FAVC": {"yes": 1, "no":0},
                  "CAEC" : {"Sometimes" : 1, "Always" : 3, "no":0,"Frequently":2},
                  "SMOKE": {"yes": 1, "no":0},
                  "SCC": {"yes": 1, "no":0},
                  "CALC" : {"Sometimes" : 1, "Always" : 3, "no":0,"Frequently":2},
                  "MTRANS" : {"Walking" :1,"Automobile" :0,"Public_Transportation" :0,"Motorbike" :0, "Bike":0},
                  "NObeyesdad": {"Insufficient_Weight":0,
                                  "Normal_Weight":1, "Overweight_Level_I":2, "Overweight_Level_II":3,"Obesity_Type_I":4, "Obesity_Type_II" : 5, "Obesity_Type_III":6}
                }

In [34]:
df.dtypes

id                                  int64
Gender                              int64
Age                               float64
Height                            float64
Weight                            float64
family_history_with_overweight      int64
FAVC                                int64
FCVC                                int64
NCP                                 int64
CAEC                                int64
SMOKE                               int64
CH2O                                int64
SCC                                 int64
FAF                                 int64
TUE                                 int64
CALC                                int64
MTRANS                              int64
NObeyesdad                         object
dtype: object

In [35]:
df = df.replace(cleanup_nums)

In [25]:
categories = df['MTRANS'].value_counts()
categories

0       2048
1         56
Bike       7
Name: MTRANS, dtype: int64

In [30]:
categories = df['NObeyesdad'].value_counts()
categories

Obesity_Type_I         351
Obesity_Type_III       324
Obesity_Type_II        297
Overweight_Level_I     290
Overweight_Level_II    290
Normal_Weight          287
Insufficient_Weight    272
Name: NObeyesdad, dtype: int64

In [36]:
df.dtypes

id                                  int64
Gender                              int64
Age                               float64
Height                            float64
Weight                            float64
family_history_with_overweight      int64
FAVC                                int64
FCVC                                int64
NCP                                 int64
CAEC                                int64
SMOKE                               int64
CH2O                                int64
SCC                                 int64
FAF                                 int64
TUE                                 int64
CALC                                int64
MTRANS                              int64
NObeyesdad                          int64
dtype: object

In [37]:
df.head()

id  Gender   Age  Height  Weight  family_history_with_overweight  FAVC  \
0   1       1  21.0    1.62    64.0                               1     0   
1   2       1  21.0    1.52    56.0                               1     0   
2   3       0  23.0    1.80    77.0                               1     0   
3   4       0  27.0    1.80    87.0                               0     0   
4   5       0  22.0    1.78    89.8                               0     0   

   FCVC  NCP  CAEC  SMOKE  CH2O  SCC  FAF  TUE  CALC  MTRANS  NObeyesdad  
0     2    3     1      0     2    0    0    1     0       0           1  
1     3    3     1      1     3    1    3    0     1       0           1  
2     2    3     1      0     2    0    2    1     2       0           1  
3     3    3     1      0     2    0    2    0     2       1           2  
4     2    1     1      0     2    0    0    0     1       0           3

In [38]:
Y = df["NObeyesdad"]

In [43]:
# X = df.drop(df["NObeyesdad"])

In [41]:
df.isnull().sum()

id                                0
Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [44]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X_train, X_test,y_train,y_test = train_test_split(df,Y,test_size=0.15)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [45]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [46]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_pred = lr.predict(X_test)
cm=confusion_matrix(y_test,Y_pred)
print(cm)
accuracy_score(y_test, Y_pred)

[[45  1  0  0  0  0  0]
 [ 0 40  1  0  0  0  0]
 [ 0  4 38  4  0  0  0]
 [ 0  0  0 40  1  0  0]
 [ 0  0  0  2 40  2  0]
 [ 0  0  0  0  1 47  0]
 [ 0  0  0  0  1  0 50]]


0.9463722397476341